function exec_close_request(self)
    scan = self.result_as_SICMScan();
    l = numel(self.GUI.ROIList.ROIs);
    scan.info.ROIs = cell(1,l);
    for roi_idx = 1:l
        r = self.GUI.ROIList.ROIs{roi_idx};
        scan.info.ROIs{roi_idx} = struct(...
            'ClassName', class(r.ROI), ...
            'Name', r.Name, ...
            'Color', r.ROI.Color, ...
            'SelectedColor', r.ROI.SelectedColor, ...
            'Position', r.ROI.Position ...
        );
    end
    if ~isempty(self.CloseCallback)
        self.CloseCallback(scan);
    else
        assignin('base','flattenResult', scan);
        fprintf(['The result was saved in the variable `flattenedResult` in the workspace.\n\n' ...
            'To assign the result to a variable, pass a function handle to the `CloseCallback` property\n'...
            'which accepts a SICM.SICMScan object (the result) as input argument.\n' ]);
    end
    delete(self.Figure);
    delete(self);
end