function start(self)
    self.gui.Window = figure( ...
        'Name', 'SICMTool', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Toolbar', 'figure', ...
        'HandleVisibility', 'off', ...
        'OuterPosition', [100, 100, 800, 600]); 
    
    self.generateMenu();
    self.generateLayout();
    self.generateAxes();
    self.generateTabs();